services:
  - type: web
    name: kallpaia-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://gamificacion-kallpaia-kappa.vercel.app
    healthCheckPath: /api/health
    autoDeploy: true
